/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API and database health */
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/staff/pin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff PIN login */
        post: operations["PinLoginController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/owner/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner or manager email/password login */
        post: operations["OwnerLoginController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token and issue a new token pair */
        post: operations["RefreshController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit-log entries for the current tenant */
        get: operations["AuditLogController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/businesses/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current tenant business profile */
        get: operations["BusinessesController_getCurrentBusiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/businesses/me/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current business setup profile */
        get: operations["BusinessesSetupController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current business setup profile */
        patch: operations["BusinessesSetupController_update"];
        trace?: never;
    };
    "/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches for the current business */
        get: operations["BranchesController_list"];
        put?: never;
        /** Create a branch */
        post: operations["BranchesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a branch */
        get: operations["BranchesController_get"];
        put?: never;
        post?: never;
        /** Deactivate a branch */
        delete: operations["BranchesController_delete"];
        options?: never;
        head?: never;
        /** Update a branch */
        patch: operations["BranchesController_update"];
        trace?: never;
    };
    "/v1/branches/{branchId}/set-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set branch as default */
        post: operations["BranchesController_setDefault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull POS terminal sync changes */
        get: operations["SyncController_pull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push POS terminal sync changes */
        post: operations["SyncController_push"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy and database is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description API is running but database is not reachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PinLoginController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    businessId: string;
                    pin: string;
                };
            };
        };
        responses: {
            /** @description Access and refresh tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        refreshToken: string;
                        /** @enum {string} */
                        tokenType: "Bearer";
                        /** @example 900 */
                        expiresIn: number;
                    };
                };
            };
            /** @description Invalid PIN. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many PIN attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OwnerLoginController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @example cafe-atlas */
                    businessSlug: string;
                };
            };
        };
        responses: {
            /** @description Access and refresh tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        refreshToken: string;
                        /** @enum {string} */
                        tokenType: "Bearer";
                        /** @example 900 */
                        expiresIn: number;
                    };
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many login attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RefreshController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New access and refresh tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        refreshToken: string;
                        /** @enum {string} */
                        tokenType: "Bearer";
                        /** @example 900 */
                        expiresIn: number;
                    };
                };
            };
            /** @description Refresh token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many refresh attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_list: {
        parameters: {
            query?: {
                before?: unknown;
                limit?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped audit-log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessesController_getCurrentBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current business profile for the tenant context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No business exists for the current tenant context. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessesSetupController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Business setup profile, legal profile, and default branch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessesSetupController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    type?: "restaurant" | "cafe" | "autre";
                    currency?: string;
                    secondaryCurrency?: string | null;
                    timezone?: string;
                    locale?: string;
                    logo?: string | null;
                    legalProfile?: {
                        legalName?: string;
                        iceNumber?: string | null;
                        rcNumber?: string | null;
                        ifNumber?: string | null;
                        patenteNumber?: string | null;
                        cnssNumber?: string | null;
                        legalAddress?: string | null;
                        legalCity?: string | null;
                        legalPostcode?: string | null;
                    };
                };
            };
        };
        responses: {
            /** @description Updated business setup profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant branch list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    /** @enum {string} */
                    status?: "active" | "inactive";
                    addressLine1?: string | null;
                    addressLine2?: string | null;
                    city?: string | null;
                    postcode?: string | null;
                    /** @default MA */
                    countryCode?: string;
                    googlePlaceId?: string | null;
                    formattedAddress?: string | null;
                    lat?: string | null;
                    lng?: string | null;
                    phone?: string | null;
                    /** Format: email */
                    email?: string | null;
                    /** Format: uri */
                    website?: string | null;
                    socialLinks?: {
                        [key: string]: unknown;
                    } | null;
                    logo?: string | null;
                    cuisineType?: string | null;
                    seatingCapacity?: number | null;
                    currency?: string | null;
                    timezone?: string | null;
                    locale?: string | null;
                };
            };
        };
        responses: {
            /** @description Created branch. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Branch not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    slug?: string;
                    /** @enum {string} */
                    status?: "active" | "inactive";
                    addressLine1?: string | null;
                    addressLine2?: string | null;
                    city?: string | null;
                    postcode?: string | null;
                    countryCode?: string;
                    googlePlaceId?: string | null;
                    formattedAddress?: string | null;
                    lat?: string | null;
                    lng?: string | null;
                    phone?: string | null;
                    /** Format: email */
                    email?: string | null;
                    /** Format: uri */
                    website?: string | null;
                    socialLinks?: {
                        [key: string]: unknown;
                    } | null;
                    logo?: string | null;
                    cuisineType?: string | null;
                    seatingCapacity?: number | null;
                    currency?: string | null;
                    timezone?: string | null;
                    locale?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated branch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_setDefault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default branch updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SyncController_pull: {
        parameters: {
            query?: {
                since?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WatermelonDB-compatible pull payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        changes: {
                            businesses?: {
                                created: {
                                    [key: string]: unknown;
                                }[];
                                updated: {
                                    [key: string]: unknown;
                                }[];
                                deleted: string[];
                            };
                            staff_members?: {
                                created: {
                                    [key: string]: unknown;
                                }[];
                                updated: {
                                    [key: string]: unknown;
                                }[];
                                deleted: string[];
                            };
                        };
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    SyncController_push: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    changes: {
                        [key: string]: unknown;
                    };
                    /** Format: date-time */
                    lastPulledAt?: string;
                };
            };
        };
        responses: {
            /** @description Push accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
}
