/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API and database health */
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/staff/pin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff PIN login */
        post: operations["PinLoginController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/owner/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner or manager email/password login */
        post: operations["OwnerLoginController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token and issue a new token pair */
        post: operations["RefreshController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit-log entries for the current tenant */
        get: operations["AuditLogController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/businesses/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current tenant business profile */
        get: operations["BusinessesController_getCurrentBusiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/businesses/me/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current business setup profile */
        get: operations["BusinessesSetupController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current business setup profile */
        patch: operations["BusinessesSetupController_update"];
        trace?: never;
    };
    "/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches for the current business */
        get: operations["BranchesController_list"];
        put?: never;
        /** Create a branch */
        post: operations["BranchesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a branch */
        get: operations["BranchesController_get"];
        put?: never;
        post?: never;
        /** Deactivate a branch */
        delete: operations["BranchesController_delete"];
        options?: never;
        head?: never;
        /** Update a branch */
        patch: operations["BranchesController_update"];
        trace?: never;
    };
    "/v1/branches/{branchId}/set-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set branch as default */
        post: operations["BranchesController_setDefault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/operating-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branch operating hours */
        get: operations["OperatingHoursController_get"];
        /** Replace branch operating hours */
        put: operations["OperatingHoursController_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment-method-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List global payment method definitions */
        get: operations["PaymentMethodsController_definitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branch payment methods */
        get: operations["PaymentMethodsController_getBranchMethods"];
        /** Replace branch payment methods */
        put: operations["PaymentMethodsController_replaceBranchMethods"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/printers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List printers and assignments for a branch */
        get: operations["PrintersController_listBranchPrinters"];
        put?: never;
        /** Manually add a branch printer */
        post: operations["PrintersController_createPrinter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/printers/{printerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a branch printer */
        delete: operations["PrintersController_deletePrinter"];
        options?: never;
        head?: never;
        /** Update branch printer metadata */
        patch: operations["PrintersController_updatePrinter"];
        trace?: never;
    };
    "/v1/branches/{branchId}/printers/{printerId}/test-print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a printer test job through the print pipeline */
        post: operations["PrintersController_enqueueTestPrint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/printer-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace branch printer assignments atomically */
        put: operations["PrintersController_replaceAssignments"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/receipt-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branch receipt settings */
        get: operations["ReceiptSettingsController_getSettings"];
        /** Upsert branch receipt settings */
        put: operations["ReceiptSettingsController_upsertSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/receipt-settings/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview unsaved branch receipt settings */
        post: operations["ReceiptSettingsController_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tax-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active Moroccan TVA rates */
        get: operations["TaxConfigController_listRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branches/{branchId}/tax-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branch tax configuration */
        get: operations["TaxConfigController_getBranchConfig"];
        /** Upsert branch tax configuration */
        put: operations["TaxConfigController_upsertBranchConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull POS terminal sync changes */
        get: operations["SyncController_pull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push POS terminal sync changes */
        post: operations["SyncController_push"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/_samples/effective-menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test-only sample proving Zod DTOs generate precise nested menu SDK types. */
        post: operations["ZodSampleController_getEffectiveMenuSample"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BusinessResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            type: string;
            city?: string | null;
            address?: string | null;
            currency: string;
            timezone: string;
            locale: string;
        };
        BusinessSetupBusinessDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            type: "restaurant" | "cafe" | "autre";
            city?: string | null;
            address?: string | null;
            logo?: string | null;
            currency: string;
            secondaryCurrency?: string | null;
            timezone: string;
            locale: string;
        };
        BusinessLegalProfileDto: {
            legalName: string;
            iceNumber?: string | null;
            rcNumber?: string | null;
            ifNumber?: string | null;
            patenteNumber?: string | null;
            cnssNumber?: string | null;
            legalAddress?: string | null;
            legalCity?: string | null;
            legalPostcode?: string | null;
        };
        DefaultBranchSummaryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            isDefault: boolean;
        };
        BusinessSetupResponseDto: {
            business: components["schemas"]["BusinessSetupBusinessDto"];
            legalProfile?: components["schemas"]["BusinessLegalProfileDto"] | null;
            defaultBranch?: components["schemas"]["DefaultBranchSummaryDto"] | null;
        };
        LegalProfileBody: {
            legalName?: string;
            iceNumber?: string | null;
            rcNumber?: string | null;
            ifNumber?: string | null;
            patenteNumber?: string | null;
            cnssNumber?: string | null;
            legalAddress?: string | null;
            legalCity?: string | null;
            legalPostcode?: string | null;
        };
        UpdateBusinessSetupBody: {
            name?: string;
            /** @enum {string} */
            type?: "restaurant" | "cafe" | "autre";
            currency?: string;
            secondaryCurrency?: string | null;
            timezone?: string;
            locale?: string;
            logo?: string | null;
            legalProfile?: components["schemas"]["LegalProfileBody"];
        };
        BranchResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            businessId: string;
            name: string;
            slug: string;
            isDefault: boolean;
            status: string;
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            postcode?: string | null;
            countryCode: string;
            googlePlaceId?: string | null;
            formattedAddress?: string | null;
            lat?: string | null;
            lng?: string | null;
            phone?: string | null;
            email?: string | null;
            website?: string | null;
            socialLinks?: {
                [key: string]: unknown;
            } | null;
            logo?: string | null;
            cuisineType?: string | null;
            seatingCapacity?: number | null;
            currency?: string | null;
            timezone?: string | null;
            locale?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BranchListResponseDto: {
            branches: components["schemas"]["BranchResponseDto"][];
        };
        BranchBody: {
            name: string;
            slug: string;
            /** @enum {string} */
            status?: "active" | "inactive";
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            postcode?: string | null;
            /** @default MA */
            countryCode: string;
            googlePlaceId?: string | null;
            formattedAddress?: string | null;
            lat?: string | null;
            lng?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            /** Format: uri */
            website?: string | null;
            socialLinks?: {
                [key: string]: unknown;
            } | null;
            logo?: string | null;
            cuisineType?: string | null;
            seatingCapacity?: number | null;
            currency?: string | null;
            timezone?: string | null;
            locale?: string | null;
        };
        UpdateBranchBody: {
            name?: string;
            slug?: string;
            /** @enum {string} */
            status?: "active" | "inactive";
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            postcode?: string | null;
            countryCode?: string;
            googlePlaceId?: string | null;
            formattedAddress?: string | null;
            lat?: string | null;
            lng?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            /** Format: uri */
            website?: string | null;
            socialLinks?: {
                [key: string]: unknown;
            } | null;
            logo?: string | null;
            cuisineType?: string | null;
            seatingCapacity?: number | null;
            currency?: string | null;
            timezone?: string | null;
            locale?: string | null;
        };
        OperatingHourResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            scheduleType: "normal" | "ramadan";
            dayOfWeek: number;
            opensAt?: string | null;
            closesAt?: string | null;
            isClosed: boolean;
            position: number;
        };
        ClosedDayResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            reason?: string | null;
        };
        OperatingHoursResponseDto: {
            /** Format: uuid */
            branchId: string;
            ramadanModeEnabled: boolean;
            normal: components["schemas"]["OperatingHourResponseDto"][];
            ramadan: components["schemas"]["OperatingHourResponseDto"][];
            closedDays: components["schemas"]["ClosedDayResponseDto"][];
        };
        OperatingHourInputDto: {
            dayOfWeek: number;
            opensAt?: string | null;
            closesAt?: string | null;
            /** @default false */
            isClosed: boolean;
            /** @default 0 */
            position: number;
        };
        ClosedDayInputDto: {
            /** Format: date */
            date: string;
            reason?: string | null;
        };
        OperatingHoursPutBodyDto: {
            /** @default false */
            ramadanModeEnabled: boolean;
            normal: components["schemas"]["OperatingHourInputDto"][];
            ramadan: components["schemas"]["OperatingHourInputDto"][];
            closedDays: components["schemas"]["ClosedDayInputDto"][];
        };
        PaymentMethodDefinitionResponseDto: {
            code: string;
            label: string;
            category: string;
            isBuiltin: boolean;
            sortOrder: number;
        };
        PaymentMethodDefinitionsResponseDto: {
            definitions: components["schemas"]["PaymentMethodDefinitionResponseDto"][];
        };
        BranchPaymentMethodResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            branchId: string;
            methodCode?: string | null;
            customName?: string | null;
            label: string;
            category: string;
            enabled: boolean;
            cashDrawerAutoOpen: boolean;
            sortOrder: number;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        BranchPaymentMethodsResponseDto: {
            /** Format: uuid */
            branchId: string;
            methods: components["schemas"]["BranchPaymentMethodResponseDto"][];
        };
        PaymentMethodInputDto: {
            methodCode?: string | null;
            customName?: string | null;
            /** @default true */
            enabled: boolean;
            /** @default false */
            cashDrawerAutoOpen: boolean;
            /** @default 0 */
            sortOrder: number;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        PaymentMethodsPutBodyDto: {
            methods: components["schemas"]["PaymentMethodInputDto"][];
        };
        PrinterResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            businessId: string;
            /** Format: uuid */
            branchId?: string | null;
            name: string;
            /** @enum {string} */
            connectionType: "manual" | "escpos_lan" | "escpos_usb" | "webprint" | "bluetooth";
            address?: string | null;
            model?: string | null;
            notes?: string | null;
            enabled: boolean;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: date-time */
            lastTestPrintAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PrinterAssignmentResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            branchId: string;
            /** Format: uuid */
            printerId: string;
            /** @enum {string} */
            role: "receipt" | "kitchen" | "bar" | "customer_copy";
            priority: number;
            /** Format: uuid */
            fallbackPrinterId?: string | null;
            enabled: boolean;
        };
        BranchPrintersResponseDto: {
            printers: components["schemas"]["PrinterResponseDto"][];
            assignments: components["schemas"]["PrinterAssignmentResponseDto"][];
        };
        CreatePrinterBodyDto: {
            name: string;
            /** @enum {string} */
            connectionType: "manual" | "escpos_lan" | "escpos_usb" | "webprint" | "bluetooth";
            address?: string | null;
            model?: string | null;
            notes?: string | null;
            /** @default true */
            enabled: boolean;
        };
        UpdatePrinterBodyDto: {
            name?: string;
            /** @enum {string} */
            connectionType?: "manual" | "escpos_lan" | "escpos_usb" | "webprint" | "bluetooth";
            address?: string | null;
            model?: string | null;
            notes?: string | null;
            enabled?: boolean;
        };
        DeletePrinterResponseDto: {
            /** Format: uuid */
            id: string;
        };
        TestPrintResponseDto: {
            /** Format: uuid */
            jobId: string;
            queued: boolean;
            /** Format: date-time */
            lastTestPrintAt: string;
        };
        PrinterAssignmentInputDto: {
            /** @enum {string} */
            role: "receipt" | "kitchen" | "bar" | "customer_copy";
            /** Format: uuid */
            printerId: string;
            /** Format: uuid */
            fallbackPrinterId?: string | null;
            /** @default 0 */
            priority: number;
            /** @default true */
            enabled: boolean;
        };
        ReplacePrinterAssignmentsBodyDto: {
            assignments: components["schemas"]["PrinterAssignmentInputDto"][];
        };
        ReceiptLineDto: {
            /** @enum {string} */
            locale: "fr" | "ar" | "darija";
            text: string;
        };
        ReceiptSettingsResponseDto: {
            logoUrl?: string | null;
            /** @default [] */
            headerLines: components["schemas"]["ReceiptLineDto"][];
            /** @default [] */
            footerLines: components["schemas"]["ReceiptLineDto"][];
            /** @default false */
            showItemCodes: boolean;
            /** @default true */
            showTaxBreakdown: boolean;
            /** @default true */
            showServerName: boolean;
            /** @default true */
            showTableNumber: boolean;
            /**
             * @default fr_only
             * @enum {string}
             */
            bilingualMode: "fr_only" | "ar_only" | "stacked" | "side_by_side";
            /**
             * @default 80mm
             * @enum {string}
             */
            paperWidth: "58mm" | "80mm";
            /**
             * @default none
             * @enum {string}
             */
            qrCodeMode: "none" | "fidelity_signup" | "social_link" | "custom_url";
            qrCodeUrl?: string | null;
            /** Format: uuid */
            branchId: string;
            isDefaultPresentation: boolean;
        };
        ReceiptSettingsPutBodyDto: {
            logoUrl?: string | null;
            /** @default [] */
            headerLines: components["schemas"]["ReceiptLineDto"][];
            /** @default [] */
            footerLines: components["schemas"]["ReceiptLineDto"][];
            /** @default false */
            showItemCodes: boolean;
            /** @default true */
            showTaxBreakdown: boolean;
            /** @default true */
            showServerName: boolean;
            /** @default true */
            showTableNumber: boolean;
            /**
             * @default fr_only
             * @enum {string}
             */
            bilingualMode: "fr_only" | "ar_only" | "stacked" | "side_by_side";
            /**
             * @default 80mm
             * @enum {string}
             */
            paperWidth: "58mm" | "80mm";
            /**
             * @default none
             * @enum {string}
             */
            qrCodeMode: "none" | "fidelity_signup" | "social_link" | "custom_url";
            qrCodeUrl?: string | null;
        };
        ReceiptPreviewResponseDto: {
            renderedText: string;
            /** @enum {string} */
            paperWidth: "58mm" | "80mm";
            columns: number;
            /** @example 120.00 */
            sampleTotal: string;
        };
        TaxRateResponseDto: {
            id: string;
            /** @example MA */
            countryCode: string;
            /** @example TVA 10% (restauration) */
            label: string;
            /** @example 10 */
            rate: number;
            isActive: boolean;
        };
        TaxRatesResponseDto: {
            rates: components["schemas"]["TaxRateResponseDto"][];
        };
        BranchTaxConfigResponseDto: {
            /** Format: uuid */
            branchId: string;
            defaultTaxRateId: string;
            /** @enum {string} */
            taxApplicationLevel: "item" | "category";
            /** @enum {string} */
            priceDisplayMode: "ttc" | "ht_plus_tva";
            serviceChargeEnabled: boolean;
            serviceChargeRate?: number | null;
            serviceChargeLabel?: string | null;
            isDefaultPresentation: boolean;
        };
        BranchTaxConfigPutBodyDto: {
            /** @example ma_tva_10 */
            defaultTaxRateId: string;
            /**
             * @default category
             * @enum {string}
             */
            taxApplicationLevel: "item" | "category";
            /**
             * @default ttc
             * @enum {string}
             */
            priceDisplayMode: "ttc" | "ht_plus_tva";
            /** @default false */
            serviceChargeEnabled: boolean;
            serviceChargeRate?: number | null;
            serviceChargeLabel?: string | null;
        };
        SampleEffectiveMenuRequestDto: {
            /** Format: uuid */
            branchId: string;
            /**
             * @default pos
             * @enum {string}
             */
            channel: "pos" | "qr" | "online";
        };
        SampleMenuCategory_Output: {
            /** Format: uuid */
            id: string;
            name: {
                [key: string]: string;
            };
            products: components["schemas"]["SampleMenuProduct_Output"][];
        };
        SampleMenuProduct_Output: {
            /** Format: uuid */
            id: string;
            name: {
                [key: string]: string;
            };
            /** @description Decimal string money value, never a JS number */
            effectivePrice: string;
            variants: components["schemas"]["SampleMenuVariant_Output"][];
        };
        SampleMenuVariant_Output: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Decimal string money value, never a JS number */
            effectivePrice: string;
            /** @enum {string} */
            pricingMode: "fixed" | "variable_pos";
        };
        SampleEffectiveMenuResponse_Output: {
            /** Format: uuid */
            branchId: string;
            /** Format: date-time */
            generatedAt: string;
            categories: components["schemas"]["SampleMenuCategory_Output"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy and database is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description API is running but database is not reachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PinLoginController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    businessId: string;
                    pin: string;
                };
            };
        };
        responses: {
            /** @description Access and refresh tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        refreshToken: string;
                        /** @enum {string} */
                        tokenType: "Bearer";
                        /** @example 900 */
                        expiresIn: number;
                    };
                };
            };
            /** @description Invalid PIN. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many PIN attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OwnerLoginController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @example cafe-atlas */
                    businessSlug: string;
                };
            };
        };
        responses: {
            /** @description Access and refresh tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        refreshToken: string;
                        /** @enum {string} */
                        tokenType: "Bearer";
                        /** @example 900 */
                        expiresIn: number;
                    };
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many login attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RefreshController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New access and refresh tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        refreshToken: string;
                        /** @enum {string} */
                        tokenType: "Bearer";
                        /** @example 900 */
                        expiresIn: number;
                    };
                };
            };
            /** @description Refresh token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many refresh attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_list: {
        parameters: {
            query?: {
                before?: unknown;
                limit?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped audit-log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessesController_getCurrentBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current business profile for the tenant context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessResponseDto"];
                };
            };
            /** @description No business exists for the current tenant context. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessesSetupController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Business setup profile, legal profile, and default branch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSetupResponseDto"];
                };
            };
        };
    };
    BusinessesSetupController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBusinessSetupBody"];
            };
        };
        responses: {
            /** @description Updated business setup profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSetupResponseDto"];
                };
            };
        };
    };
    BranchesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant branch list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchListResponseDto"];
                };
            };
        };
    };
    BranchesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchBody"];
            };
        };
        responses: {
            /** @description Created branch. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponseDto"];
                };
            };
        };
    };
    BranchesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponseDto"];
                };
            };
            /** @description Branch not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBranchBody"];
            };
        };
        responses: {
            /** @description Updated branch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponseDto"];
                };
            };
        };
    };
    BranchesController_setDefault: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default branch updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponseDto"];
                };
            };
        };
    };
    OperatingHoursController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch normal and Ramadan schedules plus closed days. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingHoursResponseDto"];
                };
            };
        };
    };
    OperatingHoursController_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatingHoursPutBodyDto"];
            };
        };
        responses: {
            /** @description Updated branch schedules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingHoursResponseDto"];
                };
            };
        };
    };
    PaymentMethodsController_definitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Built-in payment method definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodDefinitionsResponseDto"];
                };
            };
        };
    };
    PaymentMethodsController_getBranchMethods: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch payment method configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchPaymentMethodsResponseDto"];
                };
            };
        };
    };
    PaymentMethodsController_replaceBranchMethods: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentMethodsPutBodyDto"];
            };
        };
        responses: {
            /** @description Updated branch payment methods. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchPaymentMethodsResponseDto"];
                };
            };
        };
    };
    PrintersController_listBranchPrinters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchPrintersResponseDto"];
                };
            };
        };
    };
    PrintersController_createPrinter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrinterBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterResponseDto"];
                };
            };
        };
    };
    PrintersController_deletePrinter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printerId: unknown;
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletePrinterResponseDto"];
                };
            };
        };
    };
    PrintersController_updatePrinter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printerId: unknown;
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrinterBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterResponseDto"];
                };
            };
        };
    };
    PrintersController_enqueueTestPrint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printerId: unknown;
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPrintResponseDto"];
                };
            };
        };
    };
    PrintersController_replaceAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacePrinterAssignmentsBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchPrintersResponseDto"];
                };
            };
        };
    };
    ReceiptSettingsController_getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch receipt settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptSettingsResponseDto"];
                };
            };
        };
    };
    ReceiptSettingsController_upsertSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptSettingsPutBodyDto"];
            };
        };
        responses: {
            /** @description Updated branch receipt settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptSettingsResponseDto"];
                };
            };
        };
    };
    ReceiptSettingsController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptSettingsPutBodyDto"];
            };
        };
        responses: {
            /** @description Rendered sample receipt preview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptPreviewResponseDto"];
                };
            };
        };
    };
    TaxConfigController_listRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active tax rates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxRatesResponseDto"];
                };
            };
        };
    };
    TaxConfigController_getBranchConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch tax configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchTaxConfigResponseDto"];
                };
            };
        };
    };
    TaxConfigController_upsertBranchConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchTaxConfigPutBodyDto"];
            };
        };
        responses: {
            /** @description Updated branch tax configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchTaxConfigResponseDto"];
                };
            };
        };
    };
    SyncController_pull: {
        parameters: {
            query?: {
                since?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WatermelonDB-compatible pull payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        changes: {
                            businesses?: {
                                created: {
                                    [key: string]: unknown;
                                }[];
                                updated: {
                                    [key: string]: unknown;
                                }[];
                                deleted: string[];
                            };
                            staff_members?: {
                                created: {
                                    [key: string]: unknown;
                                }[];
                                updated: {
                                    [key: string]: unknown;
                                }[];
                                deleted: string[];
                            };
                        };
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    SyncController_push: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    changes: {
                        [key: string]: unknown;
                    };
                    /** Format: date-time */
                    lastPulledAt?: string;
                };
            };
        };
        responses: {
            /** @description Push accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    ZodSampleController_getEffectiveMenuSample: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleEffectiveMenuRequestDto"];
            };
        };
        responses: {
            /** @description Nested effective-menu sample with decimal-string money fields. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleEffectiveMenuResponse_Output"];
                };
            };
        };
    };
}
